### ISSUE TITLE
Generate Android and iOS projects

### ISSUE THREAD

**Issue by sgerbino** [skypjack/djinni-cmake#3]
It would be a real nice-to-have if we could generate iOS and Android projects that would automatically use the generated interface bindings.

**Comment by skypjack** [comment]
`djinni-cmake` builds the libraries for the target systems, then users have to copy them whenever they want.
What do you have in mind exactly?

**Comment by sgerbino** [comment]
./run_android.sh
 -> builds library for android
-> opens android studio with library ready for linking and djinni java files in project

./run_ios.sh
 -> builds library for ios
 -> opens Xcode with ios project and library reading for linking and djinni objcpp files in project

Yeah I oversimplified.. but that's the dream :)
Perhaps we could use python3 to script all this (since it's already a dependency)

**Comment by skypjack** [comment]
It would be great, but I suspect I'm not skilled enough to do that.
I will give it a try. If you find you can help, pull requests are welcomed.

**Comment by skypjack** [comment]
ETA 2+ years. Time to close it.
